In [1]:
### Load in NumPy
import numpy as np

In [36]:
# 1. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.
a = np.random.randint(10,22, size=(3,4))

b = np.arange(10,22).reshape((3,4))

print("First array:")
print(a)
print("Second array:")
print(b)

First array:
[[12 15 19 11]
 [16 20 11 20]
 [14 17 11 18]]
Second array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [17]:
# 2. Write a NumPy program to test whether none of the elements of a given array is zero.
x = np.array([1,2,3,4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0,1,2,3])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

arr1 = np.arange(10)
print(arr1)
print("Test if none of the elements of the said array is zero:")
print(np.all(arr1))
arr1 > 0
arr2 = arr1[arr1 > 0]
print(arr2)
print("Test if none of the elements of the said array is zero:")
print(np.all(arr2))

#arr_1 = np.arange(10)
#print(arr_1)
#arr_1.any()
#
#arr_1.all()



Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False
[0 1 2 3 4 5 6 7 8 9]
Test if none of the elements of the said array is zero:
False
[1 2 3 4 5 6 7 8 9]
Test if none of the elements of the said array is zero:
True


In [39]:
# 3. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array. 
a = np.array([1,7,13,105])
print(a)
# Count the number of elements along a given axis.
print(a.size)

# Return the length of one array element in bytes
print(a.itemsize)

# Return total bytes consumed by elements of the array
print("%d bytes" % (a.nbytes))

# Determine the size of memory occupied by the array
print("%d bytes" % (a.size * a.itemsize))


[  1   7  13 105]
4
4
16 bytes
16 bytes


In [37]:
# 4.Write a NumPy program to create an array of the integers from 30 to70.
a = np.random.randint(30,71, size=(4,11))
print(a)
print("\n")
b = np.arange(30,71)
print(b)

[[50 50 52 32 48 53 64 47 32 66 30]
 [30 47 67 33 38 34 39 65 36 59 55]
 [30 69 53 44 67 53 46 51 44 66 37]
 [70 45 45 65 42 39 51 53 40 32 64]]


[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [41]:
# 5.Write a NumPy program to reverse an array (first element becomes last).
b = np.arange(0,31)
print("Normal array", str(b))

c = b[::-1]
print("Reverse array", str(c))


Normal array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
Reverse array [30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7
  6  5  4  3  2  1  0]


In [42]:
# 6. Write a NumPy program (using numpy) to sum of all the multiples of 3 or 5 below 100. 
# Expected Output:
# [ 3 5 6 9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51 54
# 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
# 2318 

a = np.arange(1,100)

# find multiple of 3 or 5
b = a[(a % 3 == 0) | (a % 5 == 0)]
print(b[:1000])

# Returns the sum of array elements over the specified axis
print(b.sum())

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [47]:
# 7. Add the following two NumPy arrays and Modify a result array by calculating the square root of each element
#    arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
#    arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])

arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
result = arrayOne + arrayTwo
print("Add two arrays:")
print(result)
print("square root of result:")
print(np.sqrt(result))



Add two arrays:
[[20 39 33]
 [25 25 28]]
square root of result:
[[4.47213595 6.244998   5.74456265]
 [5.         5.         5.29150262]]


In [50]:
# 8. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10
a = np.arange(100,200,10).reshape((5,2))
print(a)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [61]:
# 9. Following is the 2-D array. Print max from axis 0 and min from axis 1
#    sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

a = np.array([[34,43,73],[82,22,12],[53,94,66]])
print("2d array :\n", a)

# The numpy.amax() method returns the maximum of an array or maximum along the axis(if mentioned).
max = np.amax(a,axis=0)
print("\nmax : ", max)

# The numpy.amin() function returns minimum of an array or minimum along axis(if mentioned).
min = np.amin(a, axis=1)
print("\nmin : ", min)



2d array :
 [[34 43 73]
 [82 22 12]
 [53 94 66]]

max :  [82 94 73]

min :  [34 12 53]


In [79]:
# 10. Sort following NumPy array
#    by the second row and
#    by the second column
#    sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

a = np.array([[34,43,73],[82,22,12],[53,94,66]])

# Get a specific element [row, column]
el = a[1,1]
print("\nSpecific element [1,1]: ", el)

#Get a specific row
row = a[1,:]
print("\nSpecific row:", row)

#Get a specific column
col = a[:,1]
print("\nSpecific col:", col)

# function is used to perform an indirect sort along the given axis 
# using the algorithm specified by the kind keyword. It returns an array of 
# indices of the same shape as arr that that would sort the array.
sortRow = a[:,row.argsort()]
print("Sort by second row:\n", sortRow)


sortCol = a[col.argsort()]
print("Sort by second col:\n", sortCol)





Specific element [1,1]:  22

Specific row: [82 22 12]

Specific col: [43 22 94]
Sort by second row:
 [[73 43 34]
 [12 22 82]
 [66 94 53]]
Sort by second col:
 [[82 22 12]
 [34 43 73]
 [53 94 66]]
